CLASS /appdemo/cl_libdemo_sub DEFINITION
  PUBLIC
  INHERITING FROM /appdemo/cl_libdemo
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

    CONSTANTS c_demo TYPE string VALUE 'My First Library - Subpackage' ##NO_TEXT.
ENDCLASS.



CLASS /APPDEMO/CL_LIBDEMO_SUB IMPLEMENTATION.
ENDCLASS.
