CLASS /mbtools/cl_libdemo_sub DEFINITION
  PUBLIC
  INHERITING FROM /mbtools/cl_libdemo
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

    CONSTANTS c_demo TYPE string VALUE 'My First Library - v2' ##NO_TEXT.
ENDCLASS.



CLASS /MBTOOLS/CL_LIBDEMO_SUB IMPLEMENTATION.
ENDCLASS.
